Insert Into COUNTRY_MASTER Values(1,'+91','India');
Insert Into COUNTRY_MASTER Values(2,'+1','USA');
Insert Into STATE_MASTER Values(1,1,'MAHARASHTRA');
Insert Into STATE_MASTER Values(2,1,'KARNATAKA');
Insert Into STATE_MASTER Values(3,2,'New Jersy');
Insert Into STATE_MASTER Values(4,2,'Ohio');
Insert Into CITY_MASTER Values(1,'Pune',1);
Insert Into CITY_MASTER Values(2,'Nagpur',1);
Insert Into CITY_MASTER Values(3,'Banglore',2);
Insert Into CITY_MASTER Values(4,'Mysore',2);
Insert Into CITY_MASTER Values(6,'Maywood',3);
Insert Into CITY_MASTER Values(7,'Westwood',3);
Insert Into CITY_MASTER Values(8,'Oakwood',4);
Insert Into CITY_MASTER Values(9,'Cuyahoga County',4);